version: "3.8"
services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      environment:
          RABBITMQ_DEFAULT_USER: "ubuntu"
          RABBITMQ_DEFAULT_PASS: "debian"
          RABBITMQ_VM_MEMORY_HIGH_WATERMARK: "512MiB"
      ports:
          - 5672:5672
          - 15672:15672
